### ISSUE TITLE
Doesn't bytecompile

### ISSUE THREAD

**Issue by bqv** [anticomputer/gh-notify#1]
In fact, seems to crash emacs too...

**Comment by anticomputer** [comment]
> In fact, seems to crash emacs too...

Can you provide some detail on how you are triggering the issue, what version of emacs, and which platform you are on?

**Comment by bqv** [comment]
I literally just ran gh-notify, it reliably crashes after 10 or so seconds

Managed to prevent it by removing the byte-compile error (so they are indeed related)

Linux/nixos/x86_64/pgtk/gcc/28.0.50

**Comment by anticomputer** [comment]
Interesting, will investigate.

**Comment by anticomputer** [comment]
I believe the issue has been resolved in main, please let me know if that's not the case, thanks!

**Comment by agzam** [comment]
First of all: this package is so good. It's just "mwah" 👨‍🍳 . But for some strangest and most ridiculous reason (that I can't figure out) it keeps crashing my Emacs. Like I run `gh-notify`, it opens the main buffer, it's all good, I can visit the items, etc. but if I dare running `(describe-mode)`, or even if I start typing `M-x  gh...` and as soon I press "h" after "g"  - boom, it crashes. It's so funny, for some reason I can't stop laughing.

I'm not sure what's causing this. I'm using the latest in "main".

**Comment by anticomputer** [comment]
> First of all: this package is so good. It's just "mwah" 👨‍🍳 . But for some
> strangest and most ridiculous reason (that I can't figure out) it keeps
> crashing my Emacs. Like I run `gh-notify`, it opens the main buffer, it's all
> good, I can visit the items, etc. but if I dare running `(describe-mode)`, or
> even if I start typing `M-x gh...` and as soon I press "h" after "g" - boom,
> it crashes. It's so funny, for some reason I can't stop laughing.
>
> I'm not sure what's causing this. I'm using the latest in "main".
>

which version of emacs and on what platform? I would try clearing out any stale .elc that may be laying around if you started off with an older version of the packag, if not, I'd love to see any backtrace or core dump that may be available. If your config is publicly available, let me know and I'll attempt to reproduce.

**Comment by anticomputer** [comment]
I've opened a separate issue to track this at https://github.com/anticomputer/gh-notify/issues/2
