### ISSUE TITLE
mystery crash

### ISSUE THREAD

**Issue by anticomputer** [anticomputer/gh-notify#2]
as per @agzam:

First of all: this package is so good. It's just "mwah" 👨‍🍳 . But for some strangest and most ridiculous reason (that I can't figure out) it keeps crashing my Emacs. Like I run `gh-notify`, it opens the main buffer, it's all good, I can visit the items, etc. but if I dare running `(describe-mode)`, or even if I start typing `M-x  gh...` and as soon I press "h" after "g"  - boom, it crashes. It's so funny, for some reason I can't stop laughing.

I'm not sure what's causing this. I'm using the latest in "main".

_Originally posted by @agzam in https://github.com/anticomputer/gh-notify/issues/1#issuecomment-783002226_

**Comment by anticomputer** [comment]
@agzam please add any further info to this issue so we don't spam the author of #1, thanks!

edit, as per my original reply:

which version of emacs and on what platform? I would try clearing out any stale .elc that may be laying around if you started off with an older version of the packag, if not, I'd love to see any backtrace or core dump that may be available. If your config is publicly available, let me know and I'll attempt to reproduce.

**Comment by agzam** [comment]
This maybe has little to do with the package itself. I'm using Emacs 28, built `--with-native-comp` (which is already "experimental"), on a Mac (yet another shaky foundation for Emacs to grow on). I was able to byte-compile the source, so the #1 issue even though looks very related doesn't seem to be directly affecting me. I'd say don't worry about it for now, let's just keep an eye on this thing. I'll post if I dig up something interesting.

And thank you for this amazing work. It is beautifully well done and extremely useful thing.

**Comment by agzam** [comment]
Okay, I've found something.

- It crashes only when I have it in evil-mode (I use Spacemacs)
- When I switch to Emacs-state (non-evil mode) it doesn't crash anymore, I can eval (describe-mode) without crashing Emacs
- However, it slows down **everything** significantly.
- Profiler, sadly not giving me any clues

I suspect, it has something to do with `gh-notify--self-insert-command`, but how, I still have no clue

**upd:** it also doesn't seem to crashing when I switch to "Insert" mode of Evil.

**Comment by bqv** [comment]
FYI I think I might still be experiencing this too. When I solved the byte-compile issue locally, I was testing in `emacs -Q`, hence evil was not loaded

**Comment by anticomputer** [comment]
> This maybe has little to do with the package itself. I'm using Emacs 28, built
> `--with-native-comp` (which is already "experimental"), on a Mac (yet another
> shaky foundation for Emacs to grow on). I was able to byte-compile the source,
> so the #1 issue even though looks very related doesn't seem to be directly
> affecting me. I'd say don't worry about it for now, let's just keep an eye on
> this thing. I'll post if I dig up something interesting.
>
> And thank you for this amazing work. It is beautifully well done and extremely
> useful thing.
>

Thanks!

So I suspect it might be nativecomp related as the code has some fairly intense use of slotted object access and I'm guessing there is a memory management issue cropping up in the nativecomp handling of that. Since it's a full emacs crash it might be worth floating this up to Andrea Corallo (the nativecomp dev) as a test case. I'd be curious to see (if you have time) if you could run a non-nativecomp version of your setup, my intuition is that it will run ok. If not, that might bisect it to emacs 28 itself, and that will let me poke a bit deeper there. For what it's worth, I use emacs 27.1 on macos for gh-notify with the Mitsuharu Yamamoto patch.

**Comment by anticomputer** [comment]
> FYI I think I might still be experiencing this too. When I solved the
> byte-compile issue locally, I was testing in `emacs -Q`, hence evil was not
> loaded
>

@bqv are you per chance also using nativecomp?

**Comment by bqv** [comment]
Yes

**Comment by anticomputer** [comment]
> Yes
>

Interesting, I'll give this a go on a nativecomp build this evening. If I can bisect it down to a nativecomp issue I'll file an issue with Andrea, thanks!

**Comment by anticomputer** [comment]
I was unable to reproduce on a nativecomp build, closing until someone can provide a consistent trigger of the behavior to reproduce.

**Comment by agzam** [comment]
> I was unable to reproduce on a nativecomp build

Have you tried with Evil-mode? It consistently crashes for me when the cursor is in Normal state of Evil. It's pretty annoying sometimes, I keep forgetting about this behavior.

**Comment by anticomputer** [comment]
> > I was unable to reproduce on a nativecomp build
>
> Have you tried with Evil-mode? It consistently crashes for me when the cursor
> is in Normal state of Evil. It's pretty annoying sometimes, I keep forgetting
> about this behavior.
>

Hey yeah, to double check I just set up a spacemacs on the latest nativecomp with evil-mode and I can't trigger the issue on my end switching between insert and normal mode running through gh-notify filters and visits. If you haven't updated the nativecomp build in a bit it might be worth checking to see if the issue has been addressed already.

**Comment by agzam** [comment]
I tried once again getting to the bottom of this mysterious crash. Looks like I have finally found a culprit in my config causing this shit. It's a package called ivy-rich. When ivy-rich-mode is enabled, some operations within active gh-notify buffer often crashes Emacs.

I apologize for causing so much pain and for wasting your time with this bug. I've been thinking about replacing ivy-rich with marginalia. I think I've finally nailed a reason for doing that sooner.

*update*: Hmm. This is now interesting. I just tested it out with Marginalia package. It still crashes. But only when marginalia cycled to `marginalia-annotators-heavy` - basically, whenever something shown up in the margin of Ivy/Consul, like this:

![image](https://user-images.githubusercontent.com/1091022/113451777-52649d80-93c8-11eb-87ba-b100d6c7d90b.png)


it consistently crashes Emacs. If I just type here "gh"... boom... and it crashes.

**Comment by anticomputer** [comment]
> I tried once again getting to the bottom of this mysterious crash. Looks like
> I have finally found a culprit in my config causing this shit. It's a package
> called ivy-rich. When ivy-rich-mode is enabled, some operations within active
> gh-notify buffer often crashes Emacs.
>
> I apologize for causing so much pain and for wasting your time with this
> bug. I've been thinking about replacing ivy-rich with marginalia. I think I've
> finally nailed a reason for doing that sooner.
>
> *update*: Hmm. This is now interesting. I just tested it out with Marginalia
> package. It still crashes. But only when marginalia cycled to
> `marginalia-annotators-heavy` - basically, whenever something shown up in the
> margin of Ivy/Consul, like this:
>
> ![image](https://user-images.githubusercontent.com/1091022/113451777-52649d80-93c8-11eb-87ba-b100d6c7d90b.png)
>
>
> it consistently crashes Emacs. If I just type here "gh"... boom... and it
> crashes.
>

haha well that sounds like a rabbit hole for another time :)
