### ISSUE TITLE
Different faces for issues and pull-requests

### ISSUE THREAD

**Issue by agzam** [anticomputer/gh-notify#3]
I would like to be able to quickly distinguish between different types of items in the list. Perhaps (in addition to `P` and `I` letters) having distinct faces would be nice. What do you think @anticomputer?

**Comment by anticomputer** [comment]
> I would like to be able to quickly distinguish between different types of
> items in the list. Perhaps (in addition to `P` and `I` letters) having
> distinct faces would be nice. What do you think @anticomputer?
>

sure I'll add a customization option for P vs I line items

**Comment by agzam** [comment]
Also, perhaps a way to distinguish between different states of topics - open/merged/closed/etc.

**Comment by anticomputer** [comment]
feature request added in https://github.com/anticomputer/gh-notify/commit/fbe0b2e29100dc97b538ba0405f1a3a2e7e01b51

I feel being able to customize the face for the just the type markers themselves gives enough visual processing speed in terms of rapid identification. lmk if this works for you as well.

**Comment by agzam** [comment]
Just updated. Looks beautiful. Thank you!

**Comment by anticomputer** [comment]
> Just updated. Looks beautiful. Thank you!
>

:+1:
