### ISSUE TITLE
Scroll position and Keybindings

### ISSUE THREAD

**Issue by agzam** [anticomputer/gh-notify#4]
It looks like whenever after visiting forge-topic, you close forge-topic buffer to return to gh-notify main buffer, the position changes. It would be nice if it stayed where it was before, or maybe re-centered automatically. 

Which brings me to another point. Current `C-l` keybinding in `gh-notify-mode-map` shadows one of the very important vanilla Emacs bindings - `recenter-top-bottom` (I made this discovery after trying to fix the position). I'm sure many seasoned Emacsen would appreciate if the package didn't do that. Perhaps it would be wise to do some audit of the defined keys, and minimize conflicts with native Emacs bindings. `<C-p>` is another example I can think of.

**Comment by bqv** [comment]
Not to mention, I think a few other bindings are "un-traditional" too

**Comment by anticomputer** [comment]
> It looks like whenever after visiting forge-topic, you close forge-topic
> buffer to return to gh-notify main buffer, the position changes. It would be
> nice if it stayed where it was before, or maybe re-centered automatically.
>
> Which brings me to another point. Current `C-l` keybinding in
> `gh-notify-mode-map` shadows one of the very important vanilla Emacs
> bindings - `recenter-top-bottom` (I made this discovery after trying to fix
> the position). I'm sure many seasoned Emacsen would appreciate if the package
> didn't do that. Perhaps it would be wise to do some audit of the defined keys,
> and minimize conflicts with native Emacs bindings. `<C-p>` is another example
> I can think of.
>

Point _should_ be retained after sorts and filter changes to whatever the active point was at the point of the action in the mode itself, there's explicit logic to retain point across re-displays, I did fix some of that logic to ensure gh-notify wasn't resetting to (point-min) due to the forge topic visit interrupting the gh-notify buffer redraw, so please make sure you're running the latest from main. Here both point and scroll offset for the buffer are retained properly across topic visits.

I'll move any explicitly colliding keybindings to less invasive defaults.

**Comment by agzam** [comment]
Oops, my apologies. Of course, I meant the scroll position, not the point position. There's nothing wrong with the point, but somehow (at least in my config) it would change the scroll position. And that's not happening anymore. Thank you for fixing it. I'm using `dev` branch by the way.

And I hope you don't feel extremely irritated with the issues I'm filing; this is my strange way of letting you know that I'm actively using the package. It has become my daily driver, it solves the fundamental problem of GitHub for me. The other day, I showed it to my colleagues and they were like, "whoa, I need this!". I sincerely want this project to become even more awesome and to be used by more people. I honestly can't wait for features like bulk operations, etc. I'll keep spreading the word about it. Cheers!

**Comment by anticomputer** [comment]
> Oops, my apologies. Of course, I meant the scroll position, not the point
> position. There's nothing wrong with the point, but somehow (at least in my
> config) it would change the scroll position. And that's not happening
> anymore. Thank you for fixing it. I'm using `dev` branch by the way.
>
> And I hope you don't feel extremely irritated with the issues I'm filing; this
> is my strange way of letting you know that I'm actively using the package. It
> has become my daily driver, it solves the fundamental problem of GitHub for
> me. The other day, I showed it to my colleagues and they were like, "whoa, I
> need this!". I sincerely want this project to become even more awesome and to
> be used by more people. I honestly can't wait for features like bulk
> operations, etc. I'll keep spreading the word about it. Cheers!
>

No worries, file away :) The more stutter we can remove the better.

The default keybindings have been changed to a less intrusive set in https://github.com/anticomputer/gh-notify/commit/38026eab880233ebd644838aa989b5755062d40b

**Comment by agzam** [comment]
Awesome. Thank you!
