### ISSUE TITLE
Marking topics as read from the list

### ISSUE THREAD

**Issue by agzam** [anticomputer/gh-notify#5]
Correct me if I'm wrong, but I couldn't find a way to "read" the topic without opening it, I think the package doesn't do this just yet. i.e.: you have to "visit" the topic so it gets marked as read. 
I think this is one of the features that's planned to be implemented as part of "bulk operations".

_The point of creating the issue is not to pressure the author to implement this sooner. Mainly, this is for purpose of tracking it._

**Comment by anticomputer** [comment]
yep, it's on my TODO :) i'm a bit hesitant to make it a local db flip (which would be quick and fast to support as a bulk operation) but wouldn't be sync with github.com state if there was no actual forge-visit that happened, but then I'm also hesitant to do bulk remote API interactions ... have to think on it a bit but it's on the drawing board

**Comment by agzam** [comment]
What's the workaround to clean all the unread notifications, or to reset DB?
I missed a few days of work and now have hundreds of unread items in gh-notify buffer. I can "dismiss" them in GitHub web UI, but that doesn't affect gh-notify local DB at all.

**Comment by draxil** [comment]
This would be my number one request for sure! Excellent tool though, but being able to wipe the slate occasionally would be fantastic.

**Comment by anticomputer** [comment]
https://github.com/anticomputer/gh-notify/releases/tag/v2.1.0 has some early support for read/unread db local state management (including bulk operations)
