### ISSUE TITLE
Don't remove visited topics from the list

### ISSUE THREAD

**Issue by agzam** [anticomputer/gh-notify#6]
When `gh-notify-limit-unread` is toggled (only unread topics shown in the list), after visiting a topic, and upon returning back to the list - the visited topic automatically disappears from the list. Perhaps it would be better if it doesn't re-apply the filter immediately, and would keep read topics in the list until the user explicitly resets the filter.

I for one very often find myself needing to get back to the topic I've just visited, immediately after closing it. Eye spots something there, but it doesn't register in the brain until it's too late. And I'm like: "Wait, wait, wait. What was that?... Ah, damn it, it's gone now." Generally, from the UX perspective, automatically removing things from the screen is a bad practice.

**Comment by anticomputer** [comment]
I'll make this behavior configurable, personally I prefer an auto-refresh after any state changing action to ensure that what I'm looking at is an accurate reflection of actual state (i.e. the unread topic is, in fact, now read), but I can see how that is a matter of preference

**Comment by anticomputer** [comment]
custom option provided in https://github.com/anticomputer/gh-notify/commit/3e2f7b8e4804e1edb1b2464cea671cedbbd95424

**Comment by agzam** [comment]
I tried, it works. However, I think it still should mark the read topics as "read" (show them with a face of normal weight, not bold). Maybe I'll take a look at that at some point and perhaps try to get it to a PRable state. Thank you for implementing the option var.

**Comment by agzam** [comment]
Btw, how do I get back now to "All items" after I toggled it to show only "Unread"? For some reason `gh-notify-limit-none` not working for me (with or without the var set).

**Comment by anticomputer** [comment]
> Btw, how do I get back now to "All items" after I toggled it to show only "Unread"? For some reason `gh-notify-limit-none` not working for me (with or without the var set).

Ah the read/unread filter operations is undone with prefix ... so `C-u / u RET` because they're higher up in the filter stack they have their own toggles outside of the reason filters
