### ISSUE TITLE
Push on Melpa

### ISSUE THREAD

**Issue by innerout** [anticomputer/gh-notify#7]
Since this plugin provides some nice features, it would be great to make it available on MELPA. This would make it easier to find and download the plugin.

**Comment by anticomputer** [comment]
> Since this plugin provides some nice features, it would be great to make it
> available on MELPA. This would make it easier to find and download the plugin.
>

hey, yeah I'll make this available on MELPA after it is feature complete for a first stable release which should be in a few weeks

**Comment by anticomputer** [comment]
gh-notify has been submitted to melpa and is pending approval in https://github.com/melpa/melpa/pull/7800
